# Dictioanry of indicators and their components
indicators = {
    'AccumulationDistributionLine': ['adl'],
    'AverageTrueRange': ['atr'],
    'BollingerBands': ['middle_band_bll', 'upper_band_bll', 'lower_band_bll'],
    'ChaikinMoneyFlow': ['cmf'],
    'ChaikinOscillator': ['co'],
    'ChandeMomentumOscillator': ['cmo'],
    'CommodityChannelIndex': ['cci'],
    'DetrendedPriceOscillator': ['dpo'],
    'DirectionalMovementIndex': ['+di', '-di', 'dx'],
    'DoubleExponentialMovingAverage': ['dema'],
    'EaseOfMovement': ['emv', 'emv_ma'],
    'Envelopes': ['upper_band_env', 'lower_band_env'],
    'FibonacciRetracement': ['rl_0.0', 'rl_23.6', 'rl_38.2', 'rl_50.0', 'rl_61.8', 'rl_100.0'],
    'ForecastOscillator': ['fosc'],
    'IchimokuCloud': ['tenkan_sen', 'kijun_sen', 'senkou_a', 'senkou_b'],
    'IntradayMovementIndex': ['imi'],
    'KlingerOscillator': ['ko'],
    'LinearRegressionIndicator': ['lri'],
    'LinearRegressionSlope': ['lrs'],
    'MarketFacilitationIndex': ['mfi'],
    'MassIndex': ['mi'],
    'MedianPrice': ['mp'],
    'Momentum': ['mom'],
    'MovingAverage': ['ma-simple', 'ma-exponential', 'ma-time_series', 'ma-triangular', 'ma-variable'],
    'MovingAverageConvergenceDivergence': ['macd', 'signal_line'],
    'NegativeVolumeIndex': ['nvi'],
    'OnBalanceVolume': ['obv'],
    'ParabolicSAR': ['sar'],
    'Performance': ['prf', 'target_LONG'],
    'PositiveVolumeIndex': ['pvi'],
    'PriceAndVolumeTrend': ['pvt'],
    'PriceChannel': ['highest_high', 'lowest_low'],
    'PriceOscillator': ['posc'],
    'PriceRateOfChange': ['prc'],
    'ProjectionBands': ['upper_band', 'lower_band'],
    'ProjectionOscillator': ['posc', 'trigger_line'],
    'Qstick': ['qstick'],
    'RangeIndicator': ['ri'],
    'RelativeMomentumIndex': ['rmi'],
    'RelativeStrengthIndex': ['rsi'],
    'RelativeVolatilityIndex': ['rvi'],
    'StandardDeviation': ['sd'],
    'StochasticMomentumIndex': ['smi'],
    'StochasticOscillator': ['%K', '%D'],
    'SwingIndex': ['swi'],
    'TimeSeriesForecast': ['tsf'],
    'TripleExponentialMovingAverage': ['tema'],
    'TypicalPrice': ['tp'],
    'UltimateOscillator': ['uosc'],
    'VerticalHorizontalFilter': ['vhf'],
    'VolatilityChaikins': ['vch'],
    'VolumeOscillator': ['vosc'],
    'VolumeRateOfChange': ['vrc'],
    'WeightedClose': ['wc'],
    'WildersSmoothing': ['ws'],
    'WilliamsAccumulationDistribution': ['wad'],
    'WilliamsR': ['wr']
}

# Function to get the elements associated with an indicator
def get_elements(indicaotr):
    return indicators.get(indicaotr, "No elements found for the indicator")


